void count_input(char[256], int *, int *);
void save_input(char[256], struct vec *);
void random_selection(struct vec *, int, int);
double manhattan_distance(struct vec, struct vec, int);
void k_means_plus_plus(struct vec *, int, int, int);
void Lloyds_assignment(struct vec *, struct vec *, int , int, int);
void LSH_assignment(struct vec *, struct vec *, int, int, int);
void PAM(struct vec *, struct vec *, int, int, int);
void PAMean(struct vec *, struct vec *, int, int, int);
int lsh_search(struct vec *, struct vec, struct h_func **, struct list_node ***, int *, int, int, int, int, int, int, int);
void lsh_train(struct vec *, struct h_func **, struct list_node ***, int *, int, int, int, int, int, int, int);
int modulo_calc(int, int, int);
void factors(int, int, int, int *);
unsigned int concat(struct h_func *, int);
void hash(struct list_node **, int, unsigned int, int);
